# Generated by Django 3.0.7 on 2020-07-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_remove_student_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='address',
            new_name='addressgv',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='emailgv',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='id',
            new_name='idgv',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='email',
            new_name='namegv',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='password',
            new_name='passwordgv',
        ),
    ]
