# Generated by Django 3.0.7 on 2020-07-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0003_auto_20200704_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='namegv',
            new_name='namegv1',
        ),
    ]
