# Generated by Django 3.0.7 on 2020-07-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0004_auto_20200704_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='addressgv',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='emailgv',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='idgv',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='namegv1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='passwordgv',
            new_name='password',
        ),
    ]
